# Site settings
title: SparkTrails
description: > # this means to ignore newlines until "baseurl:"
 SparkTrails is a MapReduce implementation of HypTrails and enables fast, scalable and distributed comparison of hypotheses about human trails. 
baseurl: "/sparktrails/" # the subpath of your site, e.g. /blog/
url: "https://hyptrails.github.io/sparktrails" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
